spring.application.name=servicio-votaciones
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/foro_votaciones
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# URL del servicio de publicaciones (microservicio real)
servicios.publicaciones.url=http://localhost:8081
